# Simple makefile for simple example
PROGRAM=jsmnrpc_test

# Although this test program does not depend directly on Jsmn, Jsmnrpc does
EXTRA_COMPONENTS = extras/jsmn extras/jsmnrpc
include ../../common.mk
